version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "aci-redis-1"
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: "aci-app-1"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: "aci-celery_worker-1"
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
