name: Docker Build and Push
on:
  push:
    branches:
      - prod
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        run: |
        
          docker build . -t neilrdaniel/cv3-container:${{ github.sha }}
          docker push neilrdaniel/cv3-container:${{ github.sha }}
          
        
