name: Python Lint Check
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run lint check
        run: |
          flake8 src/
       
       